services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: recommendations
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  api:
    build: ./api
    ports: ["8080:8080"]
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://user:pass@postgres:5432/recommendations
    depends_on:
      - redis
      - postgres

  frontend:
    build: ./frontend
    ports: ["80:80"]
    depends_on:
      - api

volumes:
  postgres_data: